version: "2"

linters:
  enable:
    - gocritic
    - misspell
    - revive
    - unconvert
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: var-naming
          disabled: true

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/l2D/claude-code-command-fix
